CREATE TABLE [dbo].[User]
(
	[Id] BIGINT NOT NULL PRIMARY KEY, 
	[Login] NVARCHAR(25) NOT NULL UNIQUE,
	[Email] NVARCHAR(50) NOT NULL UNIQUE,
	[EmailIsConfirmed] BIT NOT NULL DEFAULT(0),
    [FirstName] NVARCHAR(50) NULL, 
    [LastName] NVARCHAR(50) NULL, 
    [CreatedAt] DATETIME NOT NULL, 
    [RemovedAt] DATETIME NULL, 
    [PasswordHash] NVARCHAR(100) NULL,
)
