version: '3'

services:
  sqldeploy.test:
    image: sqldeploytest
    build:
      context: .
      dockerfile: SqlDeploy.Test/Dockerfile
  mssql:
    image: microsoft/mssql-server-linux
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=wiEPzF9pXnuVuejTN3p7
      - MSSQL_PID=Express
    ports:
      - 14338:1433
